export type OrderBook = {
  brkClnt: string; // "08081",
  ordValDt: string; // "NA",
  exUsrInfo: string; // "NA",
  mfdBy: string; // "NA",
  vendorCode: string; // "",
  rmk: string; // "--",
  odCrt: string; // "NA",
  ordSrc: string; // "ADMINCPPAPI_WEB",
  sipInd: string; // "NA",
  prc: string; // "22.60",
  prcTp: string; // "L",
  cnlQty: string; // 0,
  uSec: string; // "523383",
  classification: string; // "0",
  mktPro: string; // "0.00",
  ordEntTm: string; // "15-Jul-2024 15: string; //22: string; //40",
  reqId: string; // "1",
  algSeqNo: string; // "NA",
  qty: string; // 75,
  unFldSz: string; // 0,
  mktProPct: string; // "--",
  algCat: string; // "NA",
  exOrdId: string; // "1400000239193598",
  dscQty: string; // 0,
  actId: string; // "X9MPO",
  expDt: string; // "15 Jul, 2024",
  trgPrc: string; // "0.00",
  tok: string; // "71581",
  symOrdId: string; // "NA",
  fldQty: string; // 75,
  ordDtTm: string; // "15-Jul-2024 15: string; //22: string; //40",
  avgPrc: string; // "22.60",
  locId: string; // "111111111111100",
  algId: string; // "NA",
  stat: string; // "Ok",
  prod: string; // "NRML",
  exSeg: string; // "nse_fo",
  GuiOrdId: string; // "1721037160-395970-ARTPP6905D-ADMINAPI",
  usrId: string; // "ARTPP6905D",
  rptTp: string; // "NA",
  exCfmTm: string; // "15-Jul-2024 15: string; //22: string; //40",
  hsUpTm: string; // "2024/07/15 22: string; //26: string; //20",
  ordGenTp: string; // "NA",
  vldt: string; // "DAY",
  tckSz: string; // "0.05",
  ordSt: string; // "complete",
  trnsTp: string; // "S",
  refLmtPrc: string; // 0,
  coPct: string; // 0,
  nOrdNo: string; // "240715001650360",
  ordAutSt: string; // "NA",
  strategyCode: string; // "NA",
  rejRsn: string; // "--",
  boeSec: string; // 1721037160,
  expDtSsb: string; // "1721053800",
  dscQtyPct: string; // "0",
  stkPrc: string; // "12500.00",
  sym: string; // "MIDCPNIFTY",
  trdSym: string; // "MIDCPNIFTY2471512500CE",
  multiplier: string; // "1",
  precision: string; // "2",
  noMktProFlg: string; // "0.00",
  genNum: string; // "1",
  series: string; // "XX",
  prcNum: string; // "1",
  genDen: string; // "1",
  brdLtQty: string; // "75",
  mktProFlg: string; // "0.00",
  defMktProV: string; // "0.00",
  lotSz: string; // "75",
  minQty: string; // 0,
  optTp: string; // "CE",
  prcDen: string; // "1"
  ltp?: string;
};
