export type PositionBook = {
  buyAmt: string; // "1650.00",
  cfSellAmt: string; // "0.00",
  prod: string; // "NRML",
  exSeg: string; // "nse_fo",
  sqrFlg: string; // "Y",
  actId: string; // "X9MPO",
  cfBuyQty: string; // "0",
  hsUpTm: string; // "2024/07/15 22: string; //26: string; //31",
  cfSellQty: string; // "0",
  tok: string; // "71581",
  upldPrc: string; // "0.00",
  flBuyQty: string; // "75",
  flSellQty: string; // "75",
  sellAmt: string; // "1695.00",
  posFlg: string; // "true",
  cfBuyAmt: string; // "0.00",
  stkPrc: string; // "12500.00",
  trdSym: string; // "MIDCPNIFTY2471512500CE",
  sym: string; // "MIDCPNIFTY",
  multiplier: string; // "1",
  precision: string; // "2",
  expDt: string; // "15 Jul, 2024",
  type: string; // "OPTIDX",
  genNum: string; // "1",
  series: string; // "XX",
  prcNum: string; // "1",
  genDen: string; // "1",
  brdLtQty: string; // 75,
  exp: string; // "1721053800",
  lotSz: string; // "75",
  optTp: string; // "CE",
  prcDen: string; // "1"
  lp?: string;
};
